config/routes.rb
DevStatus::Application.routes.draw do

  root :to => "home#index"

  resources :repos, :only => [:index, :show]

end

app/models/github_api.rb
class GithubAPI
  def self.github_user(user_name)
    Octokit.user(user_name)
  end

  def self.org(org_name)
    Octokit.organization(org_name)
  end

  def self.org_repos(org_name)
    Octokit.organization_repositories(org_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @me = GithubAPI.github_user("RMTheCodeKid")
    @Levo = GithubAPI.gh_org("LevoLeague")
  end

  def show
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
  @org_repos = GithubAPI.
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<p>My github details</p>
<div><%= @me.id %></div>
<pre><%= @me.to_yaml %></pre>

<p>Levo's github details</p>

<p>Org Name </p>
<%= @Levo.name %>

<div class="banners">
  <a href="#">Repos</a>
  <%= link_to 'Repos', repos_path %>
  <a href="#">Makers</a>
  <a href="#">Pull Requests</a>
</div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Levo Dev.Team Status</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/header' %>
    <div class="main-content">
      <%= yield %>
    </div>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_header.html.erb
<header>
  <div class="main-nav">
    <a href="#">Development Status</a>
  </div>
</header>